## Slicing NAM model for SPECFEM3D_Cart

---

In [1]:
from sys import argv
import numpy as np
import pandas as pd
import scipy as sp
from scipy import ndimage
import matplotlib.pyplot as plt 
from matplotlib.colors import Normalize
import shapefile as sf
from scipy.interpolate import RegularGridInterpolator
from gnam.model.gridmod3d import gridmod3d as gm

### Load numpy array from NAM model

In [3]:
#this is a pickled dictionary with 4D ndarray, and 1D meta data arrays
ifilename = './rect_gron_model_full_z10_props.npz'

#Unpickle
data = np.load(ifilename)
props = data['props'] #4D ndarray

#meta data arrays
xdata = data['xd'] 
ydata = data['yd']
zdata = data['zd']

print('xd:\n',xdata)
print('yd:\n',ydata)
print('zd:\n',zdata)

# Setup Coordinate related vars
xmin = xdata[0]
dx   = xdata[1]
nx   = int(xdata[2])
xmax = xmin + (nx-1)*dx

ymin = ydata[0]
dy   = ydata[1]
ny   = int(ydata[2])
ymax = ymin + (ny-1)*dy

zmin = zdata[0]
dz   = zdata[1]
nz   = int(zdata[2])
zmax = (-zmin) + (nz-1)*dz

xd:
 [2.074625e+05 5.000000e+01 1.450000e+03]
yd:
 [5.559625e+05 5.000000e+01 1.198000e+03]
zd:
 [  0.  10. 601.]


### Create Gridded Model

In [4]:
nsub_props = props.shape[0]
axes_order = {'X':0,'Y':1,'Z':2} #this dict keeps track of axes order
gm3d = gm(props,nsub_props,axes_order,(nx,ny,nz),(dx,dy,dz),(xmin,ymin,zmin))
print('gm3d.shape:',gm3d.shape)

gm3d.shape: (3, 1450, 1198, 601)


### Subsample model to reduce memory foot print

In [5]:
gm3d.subsample(2,2,10)
print('gm3d.shape:',gm3d.shape)

gm3d.shape: (3, 725, 599, 61)


### Setup coordinate arryas for plotting and slicing

In [7]:
xc = gm3d.getLocalCoordsPointsX() + xmin
yc = gm3d.getLocalCoordsPointsY() + ymin
zc = gm3d.getLocalCoordsPointsY() + zmin
rzc = np.copy(-1*zc[::-1])

print('xc.shape:\n',xc.shape)
print('yc.shape:\n',yc.shape)
print('zc.shape:\n',zc.shape)
print('rzc.shape:\n',rzc.shape)

xc.shape:
 (725,)
yc.shape:
 (599,)
zc.shape:
 (599,)
rzc.shape:
 (599,)
